events {
    worker_connections 1024;
}

http {
    server {
        ## Escuta a porta :80, e usa o meu domínio próprio
        listen 80;
        server_name pedro-ammes.com.br www.pedro-ammes.com.br;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name pedro-ammes.com.br www.pedro-ammes.com.br;

        ## Usa a key do ssl pro meu dominio, gerei ela usando o Let's Encrypt
        ssl_certificate /etc/letsencrypt/live/pedro-ammes.com.br/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pedro-ammes.com.br/privkey.pem;

        ## Seta o root como o diretorio padrão do nginx e serve o index.html que tem dentro
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
